apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: kafka
spec:
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:9.6.2-alpine
          ports:
            - containerPort: 5432
          env:
          - name: TZ
            value: 'Asia/Seoul'
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_PASSWORD
            value: Dankook1!
